const ACTIVE_PACK_ID = "pack-2026-05-29-01";
const ACTIVE_PACK_LABEL = "2026-05-29";

function s(topic, core, why, trap, example, memory) {
  return { topic, core, why, trap, example, memory };
}

const THEME_SEEDS = {
  "Ciencia": [
    s("La crisis de replicacion cambio la forma de mirar estudios", "En varias areas se descubrio que muchos resultados publicados no se repetian bien. Eso empujo a mejorar muestras, metodos y transparencia.", "Importa porque un hallazgo aislado puede sonar fuerte y aun asi ser fragil. La confianza crece cuando otros equipos obtienen resultados parecidos.", "No significa que toda la ciencia falle. Significa que la ciencia encontro una debilidad y empezo a corregirla.", "Psicologia y biomedicina han revisado protocolos, preregistros y analisis para reducir falsos positivos.", "Un resultado repetido vale mas que un resultado llamativo."),
    s("La metrologia define como sabemos cuanto mide algo", "Medir no es solo usar aparatos: exige unidades, patrones, calibracion y acuerdos internacionales.", "Sin mediciones comparables no hay industria precisa, medicina fiable ni ciencia acumulativa.", "El numero de una medicion no basta. Tambien hay que saber su incertidumbre y como se obtuvo.", "El kilogramo se redefinio usando constantes fisicas en vez de depender de un objeto guardado en una caja.", "Medir bien es construir confianza entre laboratorios."),
    s("CRISPR no es una varita genetica perfecta", "CRISPR permite editar ADN guiando una enzima hacia una secuencia concreta, pero puede tener limites, errores y dilemas eticos.", "Importa porque abre caminos para investigacion, terapias y agricultura, pero exige control y prudencia.", "No todo rasgo depende de un solo gen. Editar una secuencia no garantiza cambiar un rasgo complejo.", "Algunas terapias experimentales buscan corregir mutaciones concretas en celulas especificas.", "Editar ADN es poderoso, pero la biologia rara vez es simple."),
    s("PCR multiplica senales minusculas", "La PCR copia fragmentos de ADN muchas veces hasta hacerlos detectables. Es una herramienta central en genetica, medicina y forense.", "Permite detectar rastros que serian invisibles con tecnicas directas.", "Amplificar tambien exige evitar contaminacion. Una pequena impureza puede multiplicarse junto con la muestra.", "Se usa para identificar patogenos, analizar parentescos o estudiar ADN antiguo.", "PCR convierte una pista pequena en informacion medible."),
    s("Los resultados negativos tambien son conocimiento", "Un experimento que no confirma una hipotesis puede descartar caminos y ahorrar trabajo a otros.", "Publicar solo resultados positivos distorsiona lo que parece funcionar.", "Un resultado negativo no siempre significa que la idea sea falsa. Puede fallar el metodo, la muestra o la medicion.", "Ensayos clinicos con efectos nulos ayudan a evitar tratamientos que parecian prometedores.", "Saber que no funciona tambien es avanzar."),
    s("Bayes ayuda a actualizar creencias con evidencia", "El razonamiento bayesiano combina lo que se sabia antes con datos nuevos para ajustar probabilidades.", "Sirve para pensar en diagnosticos, riesgos y decisiones bajo incertidumbre.", "No convierte intuiciones en verdad. Si las probabilidades iniciales son malas, el resultado puede salir torcido.", "Un test medico positivo significa cosas distintas si la enfermedad es comun o muy rara.", "La evidencia cambia probabilidades, no magia certezas."),
    s("La revision por pares es filtro, no garantia", "Expertos revisan un trabajo antes de publicarlo, pero pueden pasar por alto errores o sesgos.", "El sistema mejora la calidad media y obliga a explicar metodos, datos y conclusiones.", "No hay que tratar un paper como sentencia final. La ciencia se confirma con debate y replicacion.", "Articulos retractados muestran que incluso revistas prestigiosas pueden equivocarse.", "Peer review abre la puerta; no termina el juicio."),
    s("Los datos abiertos permiten comprobar mejor", "Compartir datos y codigo facilita que otros revisen analisis, detecten errores y reutilicen informacion.", "Aumenta transparencia y acelera descubrimientos cuando se protege la privacidad.", "Abrir datos no sirve si estan mal descritos o imposibles de interpretar.", "Bases astronomicas publicas permiten que equipos distintos encuentren patrones nuevos.", "Dato abierto sin contexto sigue siendo medio dato."),
    s("La escala cambia las reglas de la intuicion", "Lo que domina a escala humana puede no dominar en bacterias, montanas, planetas o atomos.", "Ayuda a entender por que ciertas explicaciones no se trasladan de un tamano a otro.", "La intuicion cotidiana falla cuando cambian velocidad, gravedad, viscosidad o tamano.", "Para insectos pequenos, la tension superficial del agua puede ser mas importante que para nosotros.", "Cambiar de escala es cambiar de mundo practico."),
    s("La ciencia tambien depende de buenas preguntas", "Una pregunta precisa decide que datos recoger, que comparar y que conclusion seria valida.", "Preguntas mal formuladas producen respuestas confusas aunque se usen aparatos caros.", "No toda pregunta interesante es investigable de inmediato. Debe poder traducirse en evidencia.", "Preguntar si una dieta funciona exige definir para quien, durante cuanto tiempo y con que medida.", "La pregunta correcta ahorra experimentos malos.")
  ],
  "Cultura general": [
    s("La piedra de Rosetta no tradujo magia, tradujo contexto", "Su valor fue presentar textos relacionados en varios sistemas de escritura, lo que permitio comparar patrones.", "Importa porque muestra como el conocimiento historico avanza con pistas cruzadas, no con adivinanzas.", "No fue una llave instantanea. Hizo falta comparar, probar y corregir durante anos.", "El griego conocido ayudo a interpretar jeroglificos egipcios.", "A veces una traduccion nace de alinear tres versiones."),
    s("El cero fue una tecnologia intelectual", "El cero como numero y posicion permitio escribir cantidades y operar con mucha mas potencia.", "Sin cero posicional, matematicas, contabilidad, astronomia y computacion serian mucho mas torpes.", "No es solo representar nada. Es usar la nada como pieza de calculo.", "El sistema decimal posicional se difundio desde India por el mundo islamico y luego Europa.", "El cero hizo visible el lugar vacio."),
    s("Los cafes fueron laboratorios sociales", "En varias ciudades, los cafes funcionaron como espacios de lectura, discusion, negocios y circulacion de noticias.", "Ayudaron a crear opinion publica antes de las redes modernas.", "No eran espacios neutrales para todo el mundo. Clase, genero y politica condicionaban quien participaba.", "En Londres, algunos cafes se asociaron con seguros, comercio y prensa.", "Una mesa con noticias puede cambiar una ciudad."),
    s("La escritura cambia la memoria colectiva", "Al fijar normas, cuentas y relatos, la escritura permite administrar sociedades grandes y conservar informacion.", "Hace posible comparar versiones, guardar contratos y transmitir saber mas alla de una vida.", "Escribir no garantiza verdad. Tambien fija propaganda, errores y silencios.", "Tablillas mesopotamicas registraban deudas, granos y transacciones antes que epopeyas famosas.", "La escritura empezo mucho antes que la novela."),
    s("El papel abarato la administracion", "El papel, difundido desde China, fue mas ligero y practico que muchos soportes anteriores.", "Facilito burocracias, comercio, cartas, libros y aprendizaje.", "La disponibilidad de soporte no basta. Tambien hacen falta alfabetizacion e instituciones.", "El papel transformo archivos estatales y circulacion de textos en el mundo islamico medieval.", "Una hoja barata puede sostener un imperio."),
    s("Los calendarios son acuerdos culturales", "Un calendario mezcla astronomia, religion, agricultura y poder politico.", "Organiza impuestos, fiestas, siembras, memoria y vida diaria.", "No hay un calendario natural unico. Cada sociedad decide que ciclos prioriza.", "El calendario gregoriano corrigio desfases solares acumulados del juliano.", "Medir dias tambien es ordenar sociedad."),
    s("La etiqueta social codifica jerarquias", "Saludar, sentarse, mirar, vestir o usar titulos comunica respeto, distancia y posicion.", "Permite leer relaciones sociales sin que todo se diga en voz alta.", "Lo que parece educado en un lugar puede parecer frio o invasivo en otro.", "Las formas de tratamiento formal e informal cambian mucho entre idiomas.", "Los modales son informacion cultural comprimida."),
    s("Los museos tambien cuentan historias politicas", "Seleccionan que objetos conservar, como nombrarlos y que relato construir alrededor.", "Influyen en memoria colectiva, identidad nacional y debates sobre patrimonio.", "Un objeto expuesto sin contexto puede ocultar saqueos, colonizacion o conflictos.", "Muchas instituciones revisan hoy procedencias de piezas obtenidas en contextos imperiales.", "Exponer algo tambien es interpretar el pasado."),
    s("Una lengua franca nace de necesidad practica", "Cuando grupos con idiomas distintos comercian o conviven, puede surgir una lengua comun de contacto.", "Facilita intercambio, diplomacia y circulacion de ideas.", "No siempre desplaza identidades locales; a veces convive con muchas lenguas.", "El suajili crecio como lengua de comercio en zonas de Africa oriental.", "La comunicacion crea caminos culturales."),
    s("El patrimonio inmaterial tambien se protege", "Canciones, tecnicas, fiestas, recetas, danzas y rituales pueden ser patrimonio cultural.", "Reconoce que la cultura vive en practicas, no solo en edificios.", "Proteger una tradicion no significa congelarla sin cambios.", "Tecnicas artesanales o musicas locales pueden recibir reconocimiento internacional.", "La cultura tambien se hereda haciendo.")
  ],
  "Datos curiosos": [
    s("Los tardigrados sobreviven entrando en pausa extrema", "Pueden reducir su actividad y resistir condiciones muy duras en estado de criptobiosis.", "Interesan porque revelan estrategias biologicas de resistencia al estres.", "No son invencibles en vida normal. Su resistencia depende del estado y del contexto.", "Se han estudiado por su tolerancia a desecacion, frio y radiacion.", "Sobrevivir a veces significa apagarse casi por completo."),
    s("La medusa Turritopsis puede reiniciar etapas de vida", "Ciertas medusas pueden volver de una fase adulta a una fase mas joven bajo condiciones concretas.", "Interesa para estudiar envejecimiento, regeneracion y plasticidad celular.", "No significa inmortalidad garantizada. Puede morir por enfermedades, depredacion o dano.", "El proceso se llama transdiferenciacion celular.", "Rejuvenecer biologicamente no es lo mismo que no morir."),
    s("Los pulpos tienen una inteligencia muy distribuida", "Gran parte de sus neuronas esta en los brazos, que pueden ejecutar acciones complejas.", "Muestra que la inteligencia no tiene una sola arquitectura posible.", "No hay que compararlos solo con humanos. Evolucionaron soluciones distintas.", "Un brazo puede explorar y manipular mientras el cerebro coordina decisiones generales.", "Pensar no siempre esta centralizado."),
    s("El ajolote regenera partes complejas", "Puede regenerar extremidades, tejido nervioso y partes de organos con una precision sorprendente.", "Ayuda a investigar reparacion de tejidos y desarrollo biologico.", "No se puede trasladar esa capacidad directamente a humanos.", "Laboratorios estudian como controla cicatrizacion y crecimiento.", "Regenerar no es curar una herida: es reconstruir forma."),
    s("La miel dura mucho por quimica simple", "Tiene poca agua disponible, alta acidez y compuestos que dificultan el crecimiento microbiano.", "Sirve como ejemplo de conservacion natural de alimentos.", "No toda miel mal almacenada se mantiene perfecta. La humedad puede cambiarlo todo.", "Se han encontrado mieles antiguas aun conservadas en recipientes cerrados.", "La estabilidad puede venir de quitar agua a los microbios."),
    s("Algunos mapas antiguos eran herramientas de poder", "No solo representaban territorio: afirmaban posesion, rutas, prestigio y control.", "Entender mapas historicos ayuda a leer intenciones politicas y comerciales.", "Un mapa bonito puede ser muy inexacto o interesado.", "Cartas nauticas y mapas imperiales marcaban zonas valiosas para comercio y conquista.", "Dibujar el mundo tambien puede reclamarlo."),
    s("El olor a lluvia se llama petricor", "Surge por compuestos del suelo y aceites vegetales liberados o dispersados con la lluvia.", "Es un ejemplo de como una sensacion cotidiana tiene explicacion quimica.", "No huele igual en todos los lugares. Depende de suelo, plantas y clima.", "La geosmina contribuye a olores terrosos reconocibles.", "Una palabra puede guardar una experiencia entera."),
    s("El vidrio no es simplemente solido comun", "Su estructura amorfa no esta ordenada como un cristal, aunque sea rigida.", "Interesa porque conecta quimica, materiales, arquitectura y tecnologia optica.", "La idea de que el vidrio de ventanas antiguas fluye rapido es exagerada.", "La fibra optica usa vidrio extremadamente puro para transmitir luz.", "La estructura interna decide propiedades visibles."),
    s("Algunos colores fueron tecnologias caras", "Pigmentos como ultramar o purpura tuvieron costes enormes y valor simbolico.", "El color en arte y ropa podia revelar comercio, riqueza y poder.", "Ver un color historico como decoracion moderna oculta su antiguo coste.", "El ultramar se obtenia del lapislazuli y fue muy valioso en pintura.", "A veces un color era casi una moneda."),
    s("Las huellas digitales no son el unico patron unico", "Iris, voz, venas y patrones de escritura tambien pueden identificar con distinta fiabilidad.", "Muestra como el cuerpo produce senales personales complejas.", "Un identificador biometrico no es una contrasena: si se filtra, no puedes cambiarlo facilmente.", "Sistemas de seguridad combinan varias senales para reducir errores.", "Lo unico tambien debe protegerse.")
  ],
  "Geografia": [
    s("Los estrechos maritimos concentran poder", "Canales y estrechos obligan a rutas comerciales a pasar por puntos concretos.", "Quien controla un paso puede influir en comercio, energia y seguridad.", "No basta mirar tamano de paises. A veces importa mas una franja estrecha.", "Ormuz, Malaca o Suez son puntos criticos para transporte mundial.", "La geografia pequena puede tener impacto global."),
    s("Una cuenca endorreica no llega al mar", "Algunas aguas drenan hacia lagos interiores o se evaporan antes de alcanzar el oceano.", "Esto afecta salinidad, agricultura y vulnerabilidad ambiental.", "Un lago interior puede encogerse rapido si se altera su entrada de agua.", "El mar de Aral se redujo drasticamente por desvio de rios para riego.", "No todo rio termina en el mar."),
    s("La sombra orografica crea desiertos", "Montanas obligan al aire a subir, enfriarse y soltar humedad. Al otro lado puede quedar aire seco.", "Explica contrastes climaticos fuertes en distancias cortas.", "No todo desierto nace por calor. Algunos nacen por circulacion atmosferica y relieve.", "Los Andes influyen en la aridez de zonas del oeste sudamericano.", "Una montana puede decidir donde cae la lluvia."),
    s("Las fronteras rectas suelen contar historias coloniales", "Lineas muy rectas pueden indicar decisiones de despacho mas que limites culturales o fisicos.", "Ayudan a entender conflictos, identidades divididas y administraciones artificiales.", "No toda frontera recta es automaticamente mala, pero suele exigir contexto historico.", "Muchas fronteras africanas reflejan acuerdos europeos del periodo colonial.", "Una linea en un mapa puede cortar vidas reales."),
    s("La zona economica exclusiva multiplica territorio util", "Un estado costero puede tener derechos economicos sobre recursos marinos hasta cierta distancia.", "Por eso islas pequenas pueden tener gran importancia estrategica.", "No es soberania total como en tierra firme. Hay reglas maritimas especificas.", "Pesca, minerales y energia marina dependen de estas delimitaciones.", "El mar tambien tiene geografia politica."),
    s("Las ciudades pueden hundirse por extraer agua", "Cuando se bombea demasiada agua subterranea, el terreno puede compactarse y bajar.", "Aumenta riesgos de inundacion y dana infraestructuras.", "No siempre es visible de inmediato. El descenso puede acumularse durante anos.", "Partes de Ciudad de Mexico y Jakarta han sufrido subsidencia notable.", "Una ciudad tambien depende de lo que pasa bajo sus calles."),
    s("Los monzones son sistemas estacionales", "Cambios de temperatura entre tierra y oceano alteran vientos y lluvias durante el ano.", "Sostienen agricultura y vida diaria de millones de personas.", "No son solo lluvia fuerte. Son una reorganizacion estacional de circulacion atmosferica.", "El monzon del sur de Asia condiciona cosechas y disponibilidad de agua.", "El clima tambien tiene ritmos sociales."),
    s("La altitud imita cambios de latitud", "Subir una montana suele enfriar el clima y cambiar vegetacion, como viajar hacia zonas mas polares.", "Permite que ecosistemas muy distintos convivan cerca.", "No toda montana se comporta igual. Orientacion, humedad y vientos importan.", "En regiones tropicales, pisos altitudinales separan cultivos y habitats.", "En vertical tambien se viaja por climas."),
    s("Los enclaves revelan historia politica acumulada", "Un enclave es territorio rodeado por otro estado o region. Puede nacer por herencias, tratados o conquistas.", "Complica servicios, fronteras, identidad y movilidad.", "No son rarezas sin importancia. Pueden afectar vida diaria y diplomacia.", "Baarle tiene fragmentos belgas y neerlandeses entrelazados de forma extraordinaria.", "La historia deja piezas sueltas en los mapas."),
    s("Los deltas son fertiles y vulnerables", "Se forman donde rios depositan sedimentos al llegar a mares o lagos.", "Suelen concentrar agricultura, ciudades y biodiversidad.", "Presas y subida del mar pueden reducir sedimentos y aumentar erosion.", "El delta del Mekong es clave para arroz, pesca y poblacion.", "Un delta vive del equilibrio entre rio y mar.")
  ],
  "Capitales": [
    s("Brasilia fue una capital construida para cambiar el mapa interno", "Brasil traslado su capital al interior para impulsar integracion territorial y desarrollo lejos de la costa.", "Muestra que una capital puede ser herramienta de planificacion nacional.", "Una capital planificada no garantiza por si sola igualdad regional.", "Brasilia se diseno con urbanismo moderno y funciones administrativas claras.", "Mover una capital puede ser mover el centro simbolico de un pais."),
    s("Canberra nacio como compromiso entre rivales", "Australia eligio una capital planificada entre Sydney y Melbourne para evitar favorecer a una de las dos.", "Importa porque la capitalidad a veces resuelve tensiones politicas internas.", "La ciudad mas grande no siempre es la capital mas conveniente.", "Canberra se ubica en el Territorio de la Capital Australiana.", "Una capital puede ser un acuerdo, no una ciudad dominante."),
    s("Ankara sustituyo el imaginario imperial de Estambul", "La Turquia republicana eligio Ankara como capital para representar un proyecto politico nuevo y mas centrado en Anatolia.", "Las capitales pueden marcar rupturas historicas y simbolicas.", "Estambul sigue siendo enorme e influyente, aunque no sea capital.", "El cambio acompano reformas de la republica turca en el siglo XX.", "Capital no siempre significa ciudad mas famosa."),
    s("Ottawa equilibro tensiones linguisticas y regionales", "Canada escogio Ottawa por posicion y equilibrio entre zonas anglofonas y francofonas.", "La capital puede servir como punto de balance en paises diversos.", "Toronto o Montreal son mas conocidas, pero no por eso capitales.", "Ottawa esta cerca de Ontario y Quebec, dos provincias politicamente centrales.", "La capital ideal a veces esta entre centros de poder."),
    s("Sudafrica reparte funciones capitales", "Tiene capital administrativa, legislativa y judicial en ciudades distintas.", "Muestra que la capitalidad puede dividirse segun funciones del Estado.", "No hay que buscar siempre una unica respuesta simple para cada pais.", "Pretoria, Ciudad del Cabo y Bloemfontein cumplen papeles diferentes.", "Un pais puede repartir su cabeza institucional."),
    s("Yamoussoukro no desplazo del todo a Abidjan", "Costa de Marfil tiene Yamoussoukro como capital politica, mientras Abidjan sigue siendo centro economico clave.", "Distingue capital oficial de capital funcional.", "Memorizar capitales sin contexto oculta donde se concentra la actividad real.", "Abidjan conserva peso financiero, portuario y diplomatico.", "La capital legal y la ciudad principal pueden separarse."),
    s("Dodoma convive con el peso historico de Dar es Salaam", "Tanzania designo Dodoma como capital, pero Dar es Salaam mantiene gran importancia economica y administrativa.", "Los traslados de capital pueden tardar decadas en consolidarse.", "Cambiar una sede oficial no mueve automaticamente personas, empresas e instituciones.", "Muchos paises intentan desconcentrar poder con capitales interiores.", "Una capital nueva necesita tiempo para volverse centro real."),
    s("Sucre y La Paz muestran capitalidad partida en Bolivia", "Sucre es capital constitucional y La Paz sede de gobierno y legislativo.", "Es un buen caso para entender que la politica real puede dividir funciones.", "Responder solo una ciudad puede simplificar demasiado.", "La Paz concentra mucha actividad gubernamental diaria.", "Las capitales tambien son resultado de compromisos historicos."),
    s("Abuja fue pensada como capital neutral", "Nigeria traslado la capital desde Lagos a Abuja para buscar una ubicacion mas central y menos asociada a un grupo regional.", "En paises grandes y diversos, la capital puede intentar simbolizar equilibrio.", "La neutralidad espacial no elimina por si sola tensiones sociales o politicas.", "Abuja fue planificada y desarrollada como nueva sede federal.", "Una capital puede ser un proyecto de cohesion."),
    s("Naypyidaw muestra el lado estrategico de una capital", "Myanmar traslado su capital desde Yangon a una ciudad planificada con gran escala administrativa.", "Las capitales tambien pueden responder a seguridad, control y estrategia estatal.", "Una capital enorme no implica actividad urbana vibrante.", "Sus amplias avenidas y zonas oficiales han llamado la atencion internacional.", "La forma de una capital revela prioridades de poder.")
  ],
  "Politica": [
    s("Los sistemas electorales moldean partidos", "Votar no produce los mismos resultados en sistemas mayoritarios, proporcionales o mixtos.", "Influye en si aparecen dos grandes partidos, coaliciones o parlamentos fragmentados.", "No existe sistema neutral perfecto. Cada regla premia algo y castiga algo.", "La representacion proporcional facilita partidos medianos; sistemas mayoritarios tienden a concentrar.", "La regla del juego cambia el juego."),
    s("El gerrymandering manipula fronteras electorales", "Redibujar distritos puede concentrar o dispersar votantes para favorecer a un partido.", "Puede alterar representacion sin cambiar votos totales.", "No todo cambio de distrito es manipulacion, pero el diseno puede ser decisivo.", "Distritos con formas extranas suelen despertar sospechas y requieren analisis.", "A veces el mapa vota antes que la gente."),
    s("Los veto players frenan cambios", "Actores con capacidad de bloquear decisiones hacen mas dificil aprobar reformas.", "Explica por que algunas democracias cambian lentamente aunque haya mayorias.", "Muchos vetos pueden proteger derechos o paralizar soluciones necesarias.", "Camara alta, tribunales, presidentes o gobiernos regionales pueden bloquear medidas.", "Gobernar tambien es contar bloqueos."),
    s("La burocracia puede proteger del capricho", "Funcionarios profesionales sostienen continuidad administrativa mas alla de cambios electorales.", "Sin administracion estable, las politicas publicas se vuelven improvisadas.", "Burocracia no significa siempre lentitud inutil. Tambien puede ser memoria institucional.", "Servicios fiscales, sanitarios y estadisticos dependen de equipos permanentes.", "Un Estado no funciona solo con discursos."),
    s("La legitimidad tiene varias fuentes", "Un gobierno puede buscar legitimidad por elecciones, resultados, legalidad, tradicion o carisma.", "Ayuda a entender por que algunos regimenes sobreviven sin apoyarse en una sola base.", "Ganar una eleccion no justifica ignorar derechos o reglas constitucionales.", "Un gobierno puede perder legitimidad si incumple promesas, abusa o destruye controles.", "Poder y legitimidad no son sinonimos."),
    s("El poder blando influye sin obligar", "Cultura, educacion, prestigio, tecnologia y diplomacia pueden atraer a otros paises.", "No todo poder se ejerce con ejercitos o sanciones.", "La imagen internacional puede caer rapido si contradice acciones reales.", "Becas, cine, universidades y cooperacion pueden aumentar influencia.", "A veces convencer pesa mas que imponer."),
    s("La descentralizacion reparte decisiones", "Dar competencias a regiones o municipios acerca algunas politicas a problemas locales.", "Puede mejorar adaptacion y participacion.", "Tambien puede crear desigualdad territorial si faltan recursos o coordinacion.", "Educacion, transporte o sanidad pueden organizarse de forma descentralizada.", "Acercar poder no siempre simplifica gestion."),
    s("La independencia judicial requiere reglas y cultura", "No basta escribirla en una constitucion. Tambien hacen falta nombramientos limpios, recursos y respeto institucional.", "Protege derechos y limita abusos de otros poderes.", "Jueces independientes no significan jueces sin control democratico alguno.", "Tribunales constitucionales pueden frenar leyes que violan derechos.", "La justicia necesita distancia del poder y responsabilidad ante la ley."),
    s("Las coaliciones obligan a negociar", "Cuando ningun partido tiene mayoria, formar gobierno exige pactos y concesiones.", "Puede moderar politicas o producir bloqueos segun el contexto.", "Coalicion no significa automaticamente debilidad. Puede representar mejor sociedades plurales.", "Muchos sistemas parlamentarios funcionan habitualmente con gobiernos de coalicion.", "Negociar tambien es gobernar."),
    s("La agenda politica decide que problemas existen", "Gobiernos y medios no pueden tratar todo a la vez. Seleccionar temas ya es ejercer poder.", "Un problema ignorado puede quedar fuera de presupuestos y soluciones.", "Que algo sea importante no garantiza que llegue a la agenda.", "Crisis, protestas o datos nuevos pueden mover asuntos al centro del debate.", "Antes de resolver un problema, alguien debe hacerlo visible.")
  ],
  "Historia": [
    s("El colapso de la Edad del Bronce fue una crisis conectada", "Varias sociedades del Mediterraneo oriental sufrieron destrucciones, migraciones y rupturas comerciales.", "Muestra que sistemas complejos pueden caer por combinacion de clima, guerra, economia y politica.", "No hay una unica causa segura. Las explicaciones simples se quedan cortas.", "Palacios micenicos y ciudades hititas desaparecieron o cambiaron profundamente.", "Las redes conectan prosperidad y fragilidad."),
    s("El intercambio colombino redibujo ecosistemas", "Tras 1492, plantas, animales, enfermedades y personas circularon entre continentes a escala enorme.", "Transformo dietas, poblaciones, agricultura y economias globales.", "No fue un intercambio equilibrado. Incluyo conquista, esclavitud y mortalidad masiva.", "Patata, maiz y tomate cambiaron cocinas de Europa, Asia y Africa.", "La globalizacion empezo tambien en semillas y microbios."),
    s("La peste negra altero relaciones laborales", "La gran mortalidad redujo mano de obra y aumento tensiones entre campesinos, senores y ciudades.", "Una epidemia puede cambiar salarios, leyes y estructuras sociales.", "No provoco los mismos efectos en todas partes. Las respuestas dependieron de instituciones locales.", "En algunas regiones europeas, trabajadores supervivientes pudieron negociar mejor.", "La demografia puede mover la economia."),
    s("La Casa de la Sabiduria simboliza traduccion y ciencia", "En Bagdad, traducciones y debates conectaron saber griego, persa, indio y arabe.", "Ayudo a conservar y transformar matematicas, medicina, astronomia y filosofia.", "No fue una simple copia. Hubo critica, ampliacion y creacion.", "Textos de algebra, optica y medicina circularon por redes islamicas y luego europeas.", "Traducir puede ser innovar."),
    s("La red mongola acelero conexiones euroasiaticas", "El imperio mongol facilito rutas, correos y circulacion de bienes e informacion.", "Conecto regiones lejanas y aumento contactos comerciales y diplomaticos.", "Tambien implico conquistas violentas y destrucciones enormes.", "El sistema yam organizaba relevos para mensajeros imperiales.", "Un imperio puede abrir caminos y dejar heridas."),
    s("La Revolucion Haitiana cambio la idea de libertad", "Personas esclavizadas derrotaron al sistema colonial frances y crearon Haiti independiente.", "Fue un desafio enorme al esclavismo y al orden imperial.", "A menudo se estudia menos que otras revoluciones pese a su importancia global.", "Haiti se independizo en 1804 tras una lucha compleja y brutal.", "La libertad tambien se conquisto desde plantaciones."),
    s("La Restauracion Meiji reorganizo Japon", "Japon transformo instituciones, ejercito, industria y educacion para competir con potencias occidentales.", "Muestra como un Estado puede modernizarse rapido bajo presion externa.", "No fue una occidentalizacion simple. Combino reformas nuevas con objetivos nacionales propios.", "El fin del shogunato y centralizacion imperial cambiaron la politica japonesa.", "Modernizar no significa copiar sin adaptar."),
    s("Westfalia es simbolo de soberania estatal", "Los tratados de 1648 cerraron guerras europeas y se asocian con el principio de Estados soberanos.", "Ayudan a entender la diplomacia moderna y el orden internacional.", "No crearon de golpe el sistema actual. La idea se fue construyendo con el tiempo.", "La Guerra de los Treinta Anos devasto regiones del centro de Europa.", "La paz tambien puede redibujar reglas."),
    s("La Revolucion Verde aumento cosechas y dependencias", "Nuevas variedades, fertilizantes, riego y pesticidas elevaron produccion agricola en muchos paises.", "Redujo hambrunas en algunos contextos y cambio economias rurales.", "Tambien genero dependencia de insumos, impactos ambientales y desigualdades.", "Trigo y arroz de alto rendimiento transformaron partes de Asia y America Latina.", "Mas comida puede traer nuevos problemas."),
    s("La imprenta tuvo antecedentes fuera de Europa", "Tecnicas de impresion y tipos moviles existieron en Asia antes de Gutenberg.", "Ayuda a evitar relatos donde una sola region inventa todo de cero.", "El impacto depende de idioma, mercado, alfabetizacion y demanda, no solo de la maquina.", "Corea uso tipos moviles metalicos antes de la imprenta europea de Gutenberg.", "Una invencion viaja distinto segun su ecosistema social.")
  ],
  "Religion": [
    s("El sincretismo mezcla tradiciones religiosas", "Creencias y practicas pueden combinarse cuando comunidades conviven, migran o resisten dominacion.", "Explica por que muchas religiones reales son mas hibridas que sus manuales oficiales.", "No siempre es aceptado por autoridades religiosas.", "Cultos afroamericanos combinaron elementos africanos, cristianos e indigenas en distintos contextos.", "Las religiones vividas se mueven con las personas."),
    s("Las peregrinaciones crean geografia sagrada", "Rutas y lugares santos conectan fe, economia, politica y memoria.", "Movilizan personas, construyen infraestructuras y refuerzan identidades.", "No son solo actos individuales. Tambien organizan ciudades y mercados.", "La peregrinacion a La Meca articula una comunidad musulmana global.", "Viajar puede ser una forma de pertenecer."),
    s("Los monasterios conservaron y copiaron saber", "Comunidades religiosas copiaron textos, mantuvieron bibliotecas y organizaron educacion en varios periodos.", "Su papel fue clave para transmitir obras religiosas y no religiosas.", "No fueron los unicos centros de conocimiento. Cortes, madrasas y ciudades tambien importaron.", "Scriptoria medievales producian manuscritos antes de la imprenta.", "La memoria escrita necesito manos pacientes."),
    s("La iconoclasia revela poder de las imagenes", "Destruir o prohibir imagenes religiosas muestra que las imagenes no son decoracion neutral.", "Conecta teologia, politica, control social y arte.", "No toda religion rechaza imagenes de la misma forma ni por las mismas razones.", "Conflictos bizantinos sobre iconos tuvieron consecuencias politicas y doctrinales.", "Si una imagen puede prohibirse, tambien puede gobernar emociones."),
    s("Los calendarios religiosos marcan ritmos sociales", "Ayunos, fiestas y ciclos rituales organizan trabajo, comida, memoria y comunidad.", "Influyen incluso en personas poco practicantes por vacaciones y costumbres.", "No son solo fechas espirituales. Tambien tienen efectos economicos y politicos.", "Ramadan, Pascua, Diwali o Yom Kippur ordenan tiempos colectivos distintos.", "La fe tambien se vive en calendarios."),
    s("El dharma cambia de significado segun tradicion", "En religiones indias, dharma puede referirse a deber, orden, ensenanza o camino correcto.", "Muestra que traducir conceptos religiosos a una palabra europea puede empobrecerlos.", "No conviene asumir un significado unico para todas las escuelas.", "Hinduismo, budismo y jainismo usan el termino con matices propios.", "Algunas palabras religiosas son mapas enteros."),
    s("Las ordenes sufies difundieron practica y comunidad", "El sufismo desarrollo redes de maestros, discipulos, poesia, musica y disciplina espiritual.", "Fue importante en la expansion cultural del islam en varias regiones.", "Reducirlo a misticismo exotico borra instituciones y contextos historicos.", "Tariqas sufies conectaron zonas de Africa, Asia y Oriente Medio.", "La espiritualidad tambien viaja por redes sociales."),
    s("La Reforma protestante uso tecnologia de impresion", "La imprenta ayudo a difundir panfletos, traducciones biblicas y controversias religiosas.", "Muestra como una tecnologia puede acelerar cambios doctrinales y politicos.", "La Reforma no fue solo teologia. Tambien incluyo poder, economia e identidades locales.", "Textos de Lutero circularon con rapidez para la epoca.", "Una disputa religiosa puede necesitar una tecnologia de copias."),
    s("Las religiones orales tambien preservan conocimiento", "Relatos, cantos, genealogias y rituales pueden transmitir memoria sin escritura.", "Desafia la idea de que solo lo escrito cuenta como archivo serio.", "La oralidad no es falta de estructura. Puede tener reglas muy precisas.", "Comunidades indigenas preservan historias ambientales y territoriales oralmente.", "La memoria tambien puede tener voz."),
    s("La arquitectura religiosa ordena experiencia", "Templos, mezquitas, iglesias y santuarios guian movimiento, mirada, sonido y silencio.", "El espacio construido ayuda a producir sensacion de comunidad y trascendencia.", "No es solo estilo artistico. Responde a rituales, tecnologia y poder.", "La orientacion, la luz y la acustica pueden tener sentido religioso.", "Un edificio puede ensenar como rezar.")
  ],
  "Fisica": [
    s("El teorema de Noether une simetria y conservacion", "Cuando un sistema tiene una simetria continua, aparece una cantidad conservada.", "Conecta ideas profundas: tiempo con energia, espacio con momento y rotacion con momento angular.", "No es una curiosidad matematica aislada. Es una columna de la fisica moderna.", "Si las leyes no cambian con el tiempo, se conserva la energia.", "Las simetrias revelan que no cambia."),
    s("El tunel cuantico atraviesa barreras improbables", "Particulas pueden aparecer al otro lado de barreras que clasica mente no superarian.", "Explica fenomenos en nucleos atomicos, electronica y estrellas.", "No significa teletransporte libre de objetos grandes.", "La fusion solar depende en parte de tunel cuantico entre nucleos.", "En lo pequeno, imposible puede significar poco probable."),
    s("La superconductividad elimina resistencia electrica", "Algunos materiales, a bajas temperaturas, conducen electricidad sin resistencia.", "Promete aplicaciones en imanes, sensores y transporte de energia.", "La dificultad es mantener condiciones necesarias y materiales adecuados.", "Imanes superconductores se usan en maquinas de resonancia magnetica.", "Cero resistencia es simple de decir y dificil de lograr."),
    s("La resonancia amplifica pequenas fuerzas", "Si empujas un sistema a su frecuencia natural, la oscilacion puede crecer mucho.", "Explica desde instrumentos musicales hasta fallos de estructuras.", "No toda vibracion es peligrosa. El problema es coincidir con frecuencias sensibles.", "Un columpio gana altura si empujas en el momento adecuado.", "El momento correcto puede multiplicar una fuerza pequena."),
    s("El caos determinista limita predicciones", "Sistemas con reglas claras pueden ser muy sensibles a condiciones iniciales.", "Ayuda a entender clima, fluidos y dinamicas complejas.", "Caos no significa azar total. Significa dependencia extrema de detalles.", "Pequenas diferencias iniciales en modelos meteorologicos pueden crecer rapidamente.", "Reglas simples no garantizan futuro simple."),
    s("Las transiciones de fase cambian propiedades de golpe", "Al cruzar ciertos umbrales, un material cambia de estado o comportamiento colectivo.", "Muestra como muchos elementos juntos producen propiedades nuevas.", "No se trata solo de solido, liquido y gas. Hay muchas fases fisicas.", "El magnetismo puede desaparecer por encima de una temperatura critica.", "A veces el cambio importante ocurre en el umbral."),
    s("La relatividad permite que el GPS funcione bien", "Relojes en satelites no avanzan exactamente igual que relojes en la Tierra.", "Sin correcciones relativistas, la localizacion acumularia errores.", "La relatividad no es solo teoria abstracta de agujeros negros.", "Satelites GPS corrigen efectos de velocidad y gravedad.", "Una teoria profunda puede acabar guiando tu ruta."),
    s("Los neutrinos atraviesan casi todo", "Son particulas muy ligeras que interactuan debilmente con la materia.", "Permiten estudiar procesos solares, supernovas y fisica fundamental.", "Detectarlos es dificil precisamente porque casi no chocan con nada.", "Grandes detectores subterraneos buscan destellos raros producidos por neutrinos.", "Lo que casi no interactua aun puede informar."),
    s("La entropia apunta una flecha del tiempo", "Muchos procesos naturales avanzan hacia estados mas probables y dispersos.", "Ayuda a explicar por que recordamos el pasado y no el futuro.", "Entropia no es simplemente desorden en sentido cotidiano.", "Un gas se expande espontaneamente por una habitacion, no se junta solo en una esquina.", "El tiempo se nota en lo que se dispersa."),
    s("Los campos son mas fundamentales que empujones visibles", "La fisica moderna describe influencias mediante campos que ocupan el espacio.", "Electricidad, magnetismo y gravedad se entienden mejor con campos.", "Un campo no es una sustancia visible. Se conoce por efectos medibles.", "Un iman organiza limaduras de hierro segun su campo magnetico.", "Lo invisible puede ser la estructura que manda.")
  ],
  "Astronomia": [
    s("El metodo de transito encuentra planetas por sombras", "Si un planeta pasa frente a su estrella, bloquea una fraccion pequena de luz.", "Permite descubrir exoplanetas y estimar tamano y orbita.", "No todos los planetas transitan desde nuestro punto de vista.", "Telescopios espaciales han detectado miles de candidatos usando bajadas periodicas de brillo.", "A veces un mundo se descubre por una sombra minuscula."),
    s("Las cefeidas sirven como reglas cosmicas", "Estas estrellas variables tienen relacion entre periodo de brillo y luminosidad real.", "Ayudan a medir distancias mas alla de donde sirve la paralaje directa.", "La calibracion es delicada y afecta medidas de expansion cosmica.", "Henrietta Leavitt descubrio la relacion periodo-luminosidad en cefeidas.", "Medir el universo empieza por confiar en una vela."),
    s("El fondo cosmico de microondas es luz antigua", "Es radiacion restante de una etapa temprana del universo, enfriada por la expansion.", "Ofrece una imagen del cosmos joven y pistas sobre su composicion.", "No es una foto del Big Bang exacto, sino de cuando la luz pudo viajar libremente.", "Mapas del fondo cosmico muestran pequenas variaciones de temperatura.", "El cielo conserva un eco termico muy antiguo."),
    s("La materia oscura se infiere por gravedad", "Galaxias y cumulos se comportan como si hubiera mas masa de la que vemos.", "Ayuda a explicar rotaciones galacticas y formacion de estructuras.", "Oscura no significa misteriosa por capricho; significa que no emite luz detectable directamente.", "Curvas de rotacion de galaxias fueron una pista clave.", "No ver algo no impide medir su gravedad."),
    s("La lente gravitatoria curva imagenes", "La masa puede desviar la trayectoria de la luz, actuando como una lente natural.", "Permite estudiar objetos lejanos y mapear masa invisible.", "No es una ilusion optica simple. Es geometria del espacio-tiempo.", "Cumulos de galaxias pueden producir arcos y multiples imagenes de una galaxia lejana.", "La gravedad tambien enfoca luz."),
    s("Los pulsares son relojes cosmicos", "Estrellas de neutrones giratorias emiten pulsos regulares de radiacion.", "Sirven para estudiar gravedad, materia extrema y ondas gravitacionales.", "No son faros con bombillas; son objetos compactos con campos intensos.", "El primer pulsar sorprendio por su regularidad casi artificial.", "Un cadaver estelar puede marcar segundos."),
    s("Las estrellas fabrican elementos", "Fusion y explosiones estelares producen muchos elementos mas pesados que hidrogeno y helio.", "Conecta nuestra quimica corporal con historia cosmica.", "No todos los elementos nacen en el mismo tipo de evento.", "Supernovas y fusiones de estrellas de neutrones contribuyen a elementos pesados.", "Somos materia procesada por estrellas."),
    s("La zona habitable no garantiza vida", "Indica donde podria existir agua liquida en superficie, dadas ciertas condiciones.", "Es un filtro util para buscar mundos interesantes.", "No basta estar a distancia correcta. Atmosfera, geologia y estrella importan.", "Marte y Venus muestran que ubicacion aproximada no asegura habitabilidad.", "Habitabilidad es una red de condiciones, no una franja magica."),
    s("El corrimiento al rojo revela expansion", "La luz de galaxias lejanas llega estirada hacia longitudes de onda mas rojas.", "Es una evidencia clave de que el universo se expande.", "No significa que galaxias vuelen por un espacio fijo como explosiones comunes.", "La ley de Hubble relaciona distancia y velocidad aparente de recesion.", "El espacio mismo puede cambiar las medidas de la luz."),
    s("Los meteoritos guardan memoria del sistema solar", "Algunos fragmentos rocosos conservan materiales muy antiguos.", "Permiten estudiar condiciones previas y tempranas de la formacion planetaria.", "No todos vienen de la misma fuente ni cuentan la misma historia.", "Condritas carbonaceas contienen compuestos organicos y minerales primitivos.", "Una piedra caida puede ser archivo cosmico.")
  ],
  "Sociologia": [
    s("El capital social abre puertas invisibles", "Redes de confianza y contactos pueden facilitar empleo, ayuda, informacion y seguridad.", "Explica desigualdades que no aparecen solo mirando ingresos.", "No todos los contactos valen igual ni todos tienen acceso a redes utiles.", "Una recomendacion puede cambiar una oportunidad antes de que haya entrevista.", "Las relaciones tambien son recursos."),
    s("La anomia aparece cuando fallan normas compartidas", "Durkheim uso la idea para explicar momentos de desorientacion social.", "Ayuda a pensar crisis donde las reglas antiguas no guian y las nuevas no estan claras.", "No significa falta total de normas, sino debilitamiento de orientacion comun.", "Cambios economicos bruscos pueden producir sensacion de perdida de sentido.", "Las sociedades tambien pueden perder brujula."),
    s("La burocracia organiza y despersonaliza", "Weber vio la burocracia como forma racional de administrar mediante reglas y cargos.", "Permite gestionar grandes organizaciones de forma previsible.", "Tambien puede volver decisiones rigidas y alejadas de casos humanos.", "Universidades, hospitales y Estados dependen de procedimientos burocraticos.", "La regla ayuda, pero tambien puede aplastar matices."),
    s("La socializacion ensena lo que parece natural", "Familia, escuela, medios y amistades transmiten normas, gustos y expectativas.", "Explica por que muchas costumbres se sienten obvias aunque sean aprendidas.", "No somos simples copias de la sociedad; tambien interpretamos y resistimos.", "Roles de genero, modales y ambiciones se aprenden desde pequenos.", "Lo normal suele tener historia."),
    s("La estratificacion ordena oportunidades", "Clase, genero, etnia, educacion y territorio influyen en posicion social.", "Ayuda a entender por que el esfuerzo individual no explica todo.", "No todas las desigualdades se reducen a dinero.", "Dos personas con talento similar pueden tener trayectorias distintas por origen social.", "La salida no es igual si empiezas en pisos distintos."),
    s("Las redes tienen efectos de contagio social", "Ideas, modas, miedos y comportamientos se difunden por conexiones.", "Sirve para estudiar rumores, salud, politica y consumo.", "No todo contagio social es automatico. Depende de confianza, estructura y contexto.", "Una practica puede expandirse rapido si la adoptan nodos muy conectados.", "Las redes no solo conectan: amplifican."),
    s("La desviacion depende de normas", "Un acto se considera desviado segun reglas sociales, contexto y poder de etiquetar.", "Muestra que muchas categorias morales cambian historicamente.", "No significa que todo sea relativo sin consecuencias. Significa que la reaccion social importa.", "Conductas antes perseguidas pueden normalizarse con cambios culturales.", "La sociedad no solo castiga actos; tambien los nombra."),
    s("La movilidad social mide apertura real", "Observa si personas pueden cambiar posicion educativa, economica o profesional respecto a su origen.", "Es clave para evaluar igualdad de oportunidades.", "Historias individuales de exito no prueban movilidad general alta.", "Estudios comparan ingresos de padres e hijos para estimar movilidad.", "Una escalera social importa por cuantos pueden subirla."),
    s("La secularizacion no es desaparicion simple de religion", "Puede significar perdida de autoridad institucional, cambio de practicas o privatizacion de creencias.", "Ayuda a entender sociedades donde religion sigue presente aunque cambie su papel publico.", "No ocurre igual en todos los paises ni en todas las generaciones.", "Algunos lugares tienen baja asistencia religiosa pero simbolos religiosos culturales fuertes.", "La religion puede cambiar de forma sin desaparecer."),
    s("La vida urbana produce anonimato y especializacion", "Las ciudades juntan desconocidos, oficios diversos, ritmos rapidos e instituciones densas.", "Crean oportunidades, innovacion y tambien soledad o segregacion.", "No toda ciudad genera la misma experiencia urbana.", "Barrios financieros, periferias y centros historicos producen relaciones sociales distintas.", "La ciudad es una maquina social de encuentros.")
  ],
  "Psicologia": [
    s("La disonancia cognitiva incomoda nuestras contradicciones", "Cuando acciones y creencias chocan, tendemos a justificar, cambiar ideas o evitar informacion.", "Explica por que defender errores puede sentirse mas facil que admitirlos.", "No significa hipocresia consciente. Muchas defensas son automaticas.", "Comprar algo caro puede llevarnos a exagerar sus virtudes despues.", "La mente prefiere coherencia, incluso fabricada."),
    s("La heuristica de disponibilidad exagera lo reciente", "Estimamos probabilidades segun ejemplos faciles de recordar.", "Influye en miedo, consumo de noticias y decisiones de riesgo.", "Lo memorable no siempre es lo frecuente.", "Tras ver noticias de accidentes, alguien puede sobreestimar ese peligro.", "La memoria no es una estadistica neutral."),
    s("El error fundamental de atribucion simplifica personas", "Tendemos a explicar errores ajenos por personalidad y los propios por circunstancias.", "Ayuda a entender conflictos cotidianos y juicios rapidos.", "No ocurre igual en todas las culturas ni situaciones.", "Si alguien llega tarde, pensamos que es irresponsable; si llegamos tarde, culpamos al trafico.", "Juzgamos rasgos donde a veces hay contexto."),
    s("La aversion a la perdida pesa mas que la ganancia", "Perder algo suele doler mas que lo que alegra ganar lo mismo.", "Afecta inversiones, negociaciones y decisiones de cambio.", "No significa que nadie arriesgue; depende del marco y de la persona.", "Una oferta puede parecer peor si se presenta como perdida frente a mantener lo actual.", "El miedo a perder inclina la balanza."),
    s("La repeticion espaciada vence al atracon de estudio", "Recordar en intervalos crecientes fortalece memoria mejor que repasar todo de golpe.", "Sirve para idiomas, examenes y cultura general.", "Releer pasivamente puede sentirse fluido sin producir recuerdo fuerte.", "Tarjetas de memoria funcionan mejor cuando obligan a recuperar respuestas.", "La memoria se entrena sacando informacion, no solo metiendola."),
    s("La memoria de trabajo es muy limitada", "Mantiene activa poca informacion durante tareas mentales.", "Explica por que multitarea y problemas largos saturan rapido.", "No es falta de inteligencia olvidar pasos cuando hay demasiada carga.", "Apuntar subtareas libera memoria para pensar mejor.", "La mente necesita espacio libre para razonar."),
    s("El placebo muestra que expectativa y cuerpo dialogan", "Creer que se recibe ayuda puede cambiar percepcion de dolor y algunos sintomas.", "Revela interacciones reales entre mente, contexto y fisiologia.", "No cura cualquier enfermedad ni sustituye tratamientos probados.", "El ritual medico, la confianza y el entorno pueden modular respuestas.", "La expectativa no es magia, pero tampoco es nada."),
    s("El nocebo es el reverso oscuro", "Esperar efectos negativos puede aumentar molestias o percepciones adversas.", "Importa en comunicacion medica y ansiedad por sintomas.", "No significa que el sintoma sea inventado. La experiencia puede ser real.", "Leer listas de efectos secundarios puede hacer que algunas personas noten mas sensaciones.", "Las expectativas tambien pueden doler."),
    s("La indefension aprendida reduce accion", "Tras experiencias donde nada parece funcionar, una persona puede dejar de intentar cambiar situaciones.", "Ayuda a entender bloqueo, depresion y resignacion.", "No debe usarse para culpar a quien sufre. El contexto importa.", "Experimentos clasicos mostraron pasividad despues de falta de control.", "Sentir control es combustible psicologico."),
    s("La regla pico-final distorsiona recuerdos", "Recordamos experiencias segun momentos intensos y final mas que por promedio total.", "Influye en viajes, servicios, dolor y relaciones.", "No resume toda memoria, pero predice muchos juicios retrospectivos.", "Una espera molesta puede recordarse mejor si termina con una resolucion amable.", "El final puede reescribir la experiencia.")
  ],
  "Sexologia": [
    s("El consentimiento es proceso, no contrato unico", "Debe ser libre, informado, especifico y reversible durante la interaccion.", "Protege autonomia, seguridad y confianza.", "Aceptar una cosa no significa aceptar otra ni aceptar para siempre.", "Una conversacion clara antes y durante reduce malentendidos y presion.", "Consentir es poder decir si y poder decir no."),
    s("El deseo responsivo no aparece de la nada", "Para algunas personas el deseo surge despues de intimidad, contexto seguro o estimulacion emocional.", "Evita pensar que solo el deseo espontaneo es normal.", "No tener deseo instantaneo no implica necesariamente falta de atraccion.", "El estres, cansancio o clima de pareja pueden modificar mucho el deseo.", "El deseo tambien responde al contexto."),
    s("Los guiones sexuales se aprenden culturalmente", "Ideas sobre quien debe iniciar, que se espera y que cuenta como normal vienen de medios, educacion y entorno.", "Ayuda a detectar presiones y expectativas poco realistas.", "Un guion aprendido no es una obligacion personal.", "Peliculas y pornografia pueden crear expectativas alejadas de conversaciones reales.", "Lo aprendido puede revisarse."),
    s("La salud sexual incluye bienestar y derechos", "No se limita a evitar infecciones o embarazos. Incluye respeto, informacion, placer, comunicacion y seguridad.", "Amplia la conversacion hacia relaciones sanas y autonomia.", "Hablar de salud sexual no debe reducirse a miedo o verguenza.", "Educacion sexual integral trata cuerpo, limites, anticoncepcion y emociones.", "Cuidarse tambien es saber hablar."),
    s("Muchas infecciones pueden ser asintomaticas", "Algunas ITS no muestran sintomas durante un tiempo o en algunas personas.", "Por eso las pruebas y la prevencion importan incluso sin senales visibles.", "Ausencia de sintomas no siempre significa ausencia de riesgo.", "Clamidia o VPH pueden pasar inadvertidos en ciertos casos.", "Lo invisible tambien se previene."),
    s("La anticoncepcion tiene distintos objetivos", "Metodos diferentes previenen embarazo, reducen riesgo de ITS o ambas cosas.", "Elegir bien exige informacion sobre eficacia, salud, comodidad y contexto.", "Un metodo util para una persona puede no ser ideal para otra.", "El preservativo ayuda frente a ITS; otros metodos pueden ser mas eficaces para embarazo pero no protegen igual.", "No hay metodo universal perfecto."),
    s("La pubertad tiene ritmos muy variables", "Cambios corporales y emocionales no ocurren al mismo tiempo en todas las personas.", "Normaliza diferencias y reduce comparaciones daninas.", "Variacion no significa problema automaticamente, aunque dudas medicas deben consultarse.", "Dos adolescentes de la misma edad pueden estar en etapas biologicas distintas.", "El cuerpo no sigue un calendario social exacto."),
    s("La orientacion no es lo mismo que conducta", "Atraccion, identidad y comportamiento pueden relacionarse, pero no son identicos.", "Ayuda a hablar con mas precision y respeto.", "Etiquetar desde fuera puede borrar experiencias personales.", "Una persona puede tardar tiempo en nombrar su identidad o decidir no nombrarla.", "La vivencia personal no cabe siempre en una casilla simple."),
    s("El suelo pelvico importa en salud sexual", "Musculos del suelo pelvico participan en continencia, dolor, respuesta sexual y estabilidad.", "Su cuidado puede mejorar bienestar en distintas etapas de vida.", "No todo se arregla apretando musculos. A veces hace falta relajar o tratar dolor.", "Fisioterapia especializada puede ayudar en disfunciones o recuperacion posparto.", "La salud sexual tambien es musculoesqueletica."),
    s("La comunicacion reduce lectura mental", "Hablar de preferencias, limites y preocupaciones evita asumir lo que la otra persona quiere.", "Mejora seguridad emocional y fisica.", "La verguenza puede hacer que la gente finja claridad donde hay dudas.", "Preguntas simples y respetuosas pueden cambiar una experiencia compartida.", "Nadie deberia tener que adivinarlo todo.")
  ],
  "Biologia": [
    s("La transferencia horizontal mueve genes entre especies", "Microorganismos pueden intercambiar genes sin herencia de padres a hijos.", "Explica velocidad de adaptacion y resistencia a antibioticos.", "La evolucion no es solo arbol vertical; tambien tiene puentes laterales.", "Bacterias pueden adquirir genes de resistencia mediante plasmidos.", "A veces los genes viajan de lado."),
    s("La endosimbiosis explica mitocondrias", "Una celula ancestral incorporo bacterias que acabaron viviendo dentro de ella.", "Explica por que mitocondrias tienen ADN propio y doble membrana.", "No fue una digestion normal, sino una asociacion evolutiva estable.", "Cloroplastos en plantas tienen historia endosimbiotica similar.", "La cooperacion puede volverse organo."),
    s("La convergencia evolutiva repite soluciones", "Especies no cercanas pueden desarrollar rasgos parecidos ante problemas similares.", "Muestra que el ambiente canaliza ciertas formas utiles.", "Parecido no siempre significa parentesco cercano.", "Alas de aves y murcielagos cumplen funcion similar con historias distintas.", "La evolucion puede rimar sin copiar."),
    s("Las especies clave sostienen ecosistemas", "Algunas especies tienen impacto desproporcionado sobre muchas otras.", "Perderlas puede provocar cambios en cascada.", "No siempre son las mas abundantes o llamativas.", "Depredadores superiores pueden regular poblaciones y proteger vegetacion indirectamente.", "Una pieza pequena puede sostener una red."),
    s("El quorum sensing permite decision colectiva microbiana", "Bacterias liberan y detectan senales quimicas para coordinar comportamientos.", "Muestra que microorganismos pueden actuar de forma colectiva.", "No es pensamiento consciente, sino regulacion quimica poblacional.", "Algunas bacterias activan bioluminiscencia o virulencia al alcanzar cierta densidad.", "Incluso celulas simples cuentan vecinas."),
    s("La apoptosis es muerte celular programada", "El cuerpo elimina celulas de forma controlada durante desarrollo y mantenimiento.", "Es esencial para formar estructuras y evitar danos.", "Muerte celular no siempre es accidente o enfermedad.", "Dedos separados en embriones dependen de muerte celular entre tejidos.", "Vivir tambien requiere eliminar celulas."),
    s("La regulacion genetica decide cuando usar genes", "No basta tener un gen; importa si se activa, donde y cuanto.", "Explica diferencias entre celulas con el mismo ADN.", "Pensar en genes como interruptores simples puede quedarse corto.", "Una neurona y una celula muscular comparten ADN pero usan programas distintos.", "El ADN es biblioteca; la celula decide que leer."),
    s("La microbiota influye en metabolismo e inmunidad", "Comunidades microbianas del cuerpo participan en digestion, defensa y senales quimicas.", "Cambia la forma de entender salud como ecosistema.", "No todo se soluciona tomando probioticos al azar.", "Dieta, antibioticos y enfermedades pueden alterar comunidades intestinales.", "No vivimos solos dentro del cuerpo."),
    s("El mimetismo puede enganar para sobrevivir", "Algunos organismos imitan colores, formas o conductas de otros para protegerse o cazar.", "Revela presiones evolutivas entre depredadores y presas.", "No todo parecido es mimetismo adaptativo; puede ser coincidencia.", "Algunas especies inofensivas imitan apariencia de especies venenosas.", "Parecer otra cosa puede salvar vidas."),
    s("La especiacion puede empezar con aislamiento", "Poblaciones separadas acumulan diferencias geneticas y ecologicas.", "Explica origen de biodiversidad a lo largo del tiempo.", "La separacion geografica no siempre basta; tambien importan seleccion y reproduccion.", "Islas y montanas pueden aislar poblaciones durante muchas generaciones.", "La distancia puede convertirse en diferencia biologica.")
  ],
  "Informatica": [
    s("Una funcion hash resume datos con huella fija", "Convierte informacion de cualquier tamano en una cadena de longitud determinada.", "Sirve para verificar integridad, guardar contrasenas de forma mas segura y organizar datos.", "No es cifrado: un hash no esta pensado para descifrarse.", "Descargar un archivo con hash publicado permite comprobar si se altero.", "Un hash es una huella, no una caja fuerte."),
    s("La criptografia de clave publica resolvio un problema social", "Permite comunicarse de forma segura sin compartir antes una clave secreta por un canal seguro.", "Hace posibles compras web, firmas digitales y mensajeria segura.", "No protege si el dispositivo o la persona son enganados.", "HTTPS usa intercambio de claves para crear conexiones seguras.", "La seguridad matematica aun necesita seguridad humana."),
    s("DNS traduce nombres en direcciones", "El sistema DNS convierte dominios legibles en direcciones que las maquinas pueden usar.", "Sin DNS, navegar seria mucho menos humano.", "Si DNS falla o se manipula, puedes acabar en sitios incorrectos.", "Escribir un dominio dispara consultas antes de cargar una pagina.", "Internet tambien necesita agenda de contactos."),
    s("TCP divide conversaciones en paquetes fiables", "TCP ordena, confirma y retransmite datos para que lleguen completos.", "Permite que paginas, correos y archivos funcionen sobre redes imperfectas.", "La fiabilidad tiene coste de latencia frente a otros protocolos.", "Si se pierde un paquete, TCP puede pedirlo de nuevo.", "La red conversa a trozos."),
    s("Las transacciones protegen bases de datos", "Una transaccion agrupa operaciones para que se completen juntas o se deshagan.", "Evita estados corruptos cuando algo falla a mitad.", "Sin transacciones, un pago podria descontarse sin registrarse correctamente.", "Bancos y tiendas dependen de propiedades ACID para consistencia.", "En datos criticos, medio cambio es un problema entero."),
    s("La recoleccion de basura automatiza memoria", "Algunos lenguajes liberan memoria que ya no se usa mediante garbage collection.", "Reduce errores comunes y acelera desarrollo.", "No elimina todos los problemas de rendimiento o fugas.", "JavaScript y Java usan recolectores que pausan o trabajan junto al programa.", "Automatizar memoria no la vuelve gratis."),
    s("El control de versiones guarda historia del codigo", "Herramientas como Git registran cambios, ramas y autores.", "Permite colaborar, volver atras y entender decisiones.", "No reemplaza buenos mensajes ni pruebas.", "Una rama permite experimentar sin romper la version principal.", "El codigo necesita memoria organizada."),
    s("Las condiciones de carrera dependen del tiempo", "Dos procesos acceden a un recurso compartido y el resultado cambia segun el orden exacto.", "Producen errores dificiles de reproducir.", "Que algo funcione una vez no demuestra que sea seguro en concurrencia.", "Dos usuarios comprando el ultimo producto a la vez pueden revelar una carrera.", "Cuando el tiempo decide, el bug se esconde."),
    s("La compresion aprovecha patrones", "Reducir datos consiste en representar redundancias de forma mas eficiente.", "Hace posibles streaming, copias rapidas y almacenamiento mas barato.", "Comprimir con perdida sacrifica informacion para ahorrar mucho mas.", "JPEG elimina detalles visuales que suelen notarse menos.", "Guardar menos empieza por detectar repeticion."),
    s("Los modelos de IA heredan datos y objetivos", "Un sistema aprende patrones de los datos y optimiza una meta definida.", "Si datos u objetivos estan sesgados, el resultado tambien puede estarlo.", "No basta decir que una maquina fue objetiva.", "Un modelo entrenado con historiales injustos puede repetir decisiones injustas.", "La IA automatiza patrones, no sabiduria.")
  ],
  "Economia": [
    s("Las externalidades son costes fuera del precio", "Una actividad puede afectar a terceros sin que ese efecto aparezca en el precio de mercado.", "Explica contaminacion, ruido, vacunas o investigacion.", "Un mercado puede ser eficiente para compradores y vendedores pero danino para otros.", "Una fabrica que contamina un rio impone costes a quienes viven abajo.", "El precio no siempre cuenta toda la historia."),
    s("El riesgo moral aparece cuando otro paga el dano", "Si alguien esta protegido de consecuencias, puede asumir mas riesgos.", "Importa en seguros, bancos y contratos.", "No significa que todo seguro sea malo; hay que disenar incentivos.", "Un conductor asegurado podria ser menos cuidadoso si no hay franquicia o controles.", "La proteccion cambia conducta."),
    s("La seleccion adversa ocurre con informacion desigual", "Cuando una parte sabe mas que otra, los malos riesgos pueden dominar el mercado.", "Explica problemas en seguros, coches usados y credito.", "La falta de informacion puede destruir intercambios utiles.", "Si solo los clientes con alto riesgo compran cierto seguro, el precio sube y expulsa a otros.", "Cuando no se distingue calidad, la mala calidad gana espacio."),
    s("La ventaja comparativa no exige ser el mejor", "Un pais o persona se especializa donde renuncia a menos frente a alternativas.", "Explica por que el comercio puede beneficiar incluso si una parte es mas productiva en todo.", "No dice que todos ganen automaticamente dentro de cada pais.", "Alguien excelente en dos tareas puede delegar una si su tiempo rinde mas en otra.", "El coste relativo decide especializacion."),
    s("Las expectativas pueden mover inflacion", "Si empresas y trabajadores esperan subidas de precios, ajustan salarios y precios anticipadamente.", "La economia no solo responde a datos actuales, tambien a creencias sobre el futuro.", "No toda inflacion viene de expectativas; energia, oferta y demanda tambien importan.", "Bancos centrales comunican objetivos para influir en expectativas.", "Lo que se espera puede ayudar a producir lo que ocurre."),
    s("Los bienes publicos son dificiles de cobrar individualmente", "Son no excluibles y no rivales, como defensa nacional o faros clasicos.", "El mercado puede producirlos por debajo de lo necesario.", "Publico no significa gratuito ni estatal en todos los sentidos.", "Si todos se benefician de un faro, algunos pueden intentar no pagar.", "Compartir beneficio complica financiar."),
    s("La liquidez mide facilidad de convertir en dinero", "Un activo liquido se vende rapido sin perder mucho valor.", "Importa en crisis, inversiones y supervivencia financiera.", "Ser rico en activos no significa tener efectivo disponible.", "Una vivienda puede valer mucho pero tardar en venderse.", "Valor y disponibilidad no son lo mismo."),
    s("El problema principal-agente separa intereses", "Quien decide por otro puede tener incentivos distintos del propietario o ciudadano.", "Aparece en empresas, politica y contratos.", "No se resuelve solo confiando en buena voluntad.", "Accionistas, directivos y trabajadores pueden perseguir objetivos distintos.", "Delegar poder exige disenar controles."),
    s("Los efectos de red hacen mas valioso lo usado por muchos", "Un servicio gana utilidad cuando mas personas lo adoptan.", "Explica plataformas, redes sociales, idiomas y sistemas de pago.", "Puede crear monopolios o encierros aunque existan alternativas tecnicamente mejores.", "Una app de mensajeria vale poco si nadie de tu entorno la usa.", "La utilidad puede estar en la multitud."),
    s("La productividad no es trabajar mas horas", "Mide produccion por recurso usado, como tiempo, capital o energia.", "Aumenta con organizacion, tecnologia, educacion e infraestructura.", "Exigir mas horas puede bajar productividad si agota o empeora calidad.", "Una herramienta que automatiza tareas puede producir mas con el mismo equipo.", "Trabajar mejor no siempre es trabajar mas.")
  ],
  "Filosofia": [
    s("El problema de Gettier cuestiona conocer como creencia verdadera justificada", "Casos imaginarios muestran que alguien puede tener una creencia verdadera y justificada por suerte.", "Obliga a refinar que significa saber algo.", "No es un juego vacio: afecta confianza, prueba y conocimiento.", "Creer algo por una razon equivocada que casualmente resulta verdad puede no ser conocimiento.", "La verdad por suerte no basta."),
    s("El velo de ignorancia busca justicia imparcial", "Rawls propone imaginar reglas sociales sin saber que lugar ocuparas en la sociedad.", "Ayuda a pensar instituciones sin favorecer tu posicion actual.", "No elimina todos los desacuerdos sobre justicia.", "Si no sabes si naceras rico o pobre, eliges protecciones basicas mas fuertes.", "Disenar reglas cambia si podrias ser cualquiera."),
    s("El imperativo categorico exige universalizar acciones", "Kant pregunta si la maxima de una accion podria valer como ley universal.", "Mueve la etica desde consecuencias hacia deber y respeto.", "Aplicarlo no siempre da respuestas faciles.", "Mentir por conveniencia falla si todos universalizan esa regla.", "Actua como si tu regla pudiera gobernar a todos."),
    s("El utilitarismo mira consecuencias agregadas", "Evalua acciones por su capacidad de aumentar bienestar o reducir sufrimiento.", "Ofrece una forma clara de comparar politicas y decisiones.", "Puede chocar con derechos individuales si solo mira suma total.", "Una politica sanitaria puede evaluarse por vidas salvadas y danos reducidos.", "Maximizar bien comun exige cuidar a quien paga el coste."),
    s("El problema de induccion pregunta por que confiamos en patrones", "Hume senalo que el futuro no esta logicamente garantizado por el pasado.", "Es central para ciencia, prediccion y aprendizaje.", "No impide actuar, pero muestra que la costumbre no es demostracion absoluta.", "Que el sol haya salido siempre no prueba logicamente que saldra manana.", "La experiencia guia, pero no demuestra todo."),
    s("El barco de Teseo cuestiona identidad en el cambio", "Si cambias todas las partes de un objeto, surge la duda de si sigue siendo el mismo.", "Sirve para pensar personas, instituciones, cuerpos y memoria.", "No hay una unica respuesta obvia; depende de que criterio uses.", "Una empresa que cambia empleados, sede y productos puede seguir teniendo el mismo nombre.", "La identidad puede estar en continuidad, forma o relato."),
    s("La habitacion china cuestiona comprension en maquinas", "Searle imagina seguir reglas para responder en chino sin entender chino.", "Plantea diferencia entre manipular simbolos y comprender significados.", "No zanja por completo el debate sobre inteligencia artificial.", "Un sistema puede producir respuestas correctas sin experiencia subjetiva clara.", "Responder bien no siempre prueba entender."),
    s("La falsabilidad separa ciencia de explicaciones blindadas", "Popper defendio que una teoria cientifica debe arriesgarse a ser refutada.", "Ayuda a detectar afirmaciones que explican todo y por eso no prueban nada.", "No toda ciencia funciona con falsacion simple de una frase.", "Una prediccion arriesgada permite someter una teoria a prueba real.", "Una idea invulnerable puede ser inutil."),
    s("La fenomenologia estudia experiencia vivida", "Pregunta como aparecen el mundo, el cuerpo, el tiempo y los otros en la conciencia.", "Ofrece herramientas para pensar percepcion, medicina, arte y tecnologia.", "No es simplemente introspeccion libre; tiene metodo descriptivo.", "El dolor se entiende distinto como senal biologica y como experiencia vivida.", "La realidad tambien se estudia desde como se muestra."),
    s("La paradoja del tranvia revela choques morales", "Casos hipoteticos comparan consecuencias, intenciones y responsabilidad.", "Sirven para ver que principios usamos al decidir.", "No sustituyen problemas reales con contexto completo.", "Mucha gente juzga distinto desviar un tranvia que empujar a una persona.", "Las intuiciones morales tienen estructura, no siempre coherencia.")
  ],
  "Salud": [
    s("El ritmo circadiano regula mas que el sueno", "Luz, comida, actividad y horarios influyen en relojes biologicos.", "Afecta energia, metabolismo, atencion y descanso.", "Dormir horas suficientes con horarios caoticos puede no sentirse igual.", "Exponerse a luz brillante por la manana ayuda a sincronizar el reloj interno.", "El cuerpo tambien lee la hora."),
    s("La presion arterial alta puede no avisar", "Muchas personas no notan sintomas aunque la presion este elevada.", "Por eso medirla periodicamente ayuda a prevenir problemas cardiovasculares.", "Sentirse bien no siempre significa que todo parametro este bien.", "Controles rutinarios detectan riesgos antes de que den senales.", "Lo silencioso tambien cuenta en salud."),
    s("La fibra alimenta ecosistemas intestinales", "Ciertos tipos de fibra sirven de sustrato para bacterias beneficiosas.", "Influye en transito, saciedad, glucosa y salud metabolica.", "Subir fibra de golpe puede causar molestias; conviene progresar.", "Legumbres, avena, frutas y verduras aportan fibras diferentes.", "Comer para ti tambien es comer para tu microbiota."),
    s("El entrenamiento de fuerza protege autonomia", "Mantener musculo ayuda a movilidad, metabolismo y prevencion de fragilidad.", "No es solo estetica ni deporte avanzado.", "La tecnica y progresion importan mas que levantar mucho al inicio.", "Sentadillas, empujes y tracciones adaptadas pueden servir con poco material.", "La fuerza es ahorro para el futuro."),
    s("La vacuna tambien protege a la comunidad", "Al reducir contagios o gravedad, puede ayudar a proteger a personas vulnerables.", "La salud publica depende de decisiones individuales acumuladas.", "La proteccion comunitaria varia segun enfermedad y vacuna.", "Altas coberturas dificultan que ciertos patogenos circulen.", "Cuidarse puede tener efecto alrededor."),
    s("El protector solar no es solo para quemaduras", "La radiacion ultravioleta contribuye a envejecimiento cutaneo y riesgo de cancer de piel.", "La prevencion diaria puede importar aunque no haya playa.", "Nubes y frio no eliminan exposicion UV.", "UVA atraviesa mas y puede afectar piel sin quemadura inmediata.", "El sol cuenta incluso cuando no arde."),
    s("El antibiotico mal usado crea problemas futuros", "Usar antibioticos sin necesidad favorece bacterias resistentes.", "La resistencia reduce opciones para infecciones reales.", "No completar o automedicar tratamientos puede ser peligroso.", "Infecciones virales como resfriados comunes no se tratan con antibioticos.", "Cada antibiotico usado mal puede quitar poder al siguiente."),
    s("El descanso afecta regulacion emocional", "Dormir poco aumenta irritabilidad, impulsividad y dificultad para concentrarse.", "La salud mental no se separa de habitos biologicos.", "Dormir no resuelve todos los problemas, pero empeora muchos cuando falta.", "Una mala noche puede hacer que conflictos pequenos parezcan enormes.", "A veces la mente necesita cama antes que debate."),
    s("El cribado medico tiene beneficios y costes", "Detectar temprano puede salvar vidas, pero tambien puede producir falsos positivos o sobrediagnostico.", "Ayuda a decidir pruebas segun edad, riesgo y evidencia.", "Mas pruebas no siempre significan mejor salud.", "Programas de cribado se recomiendan cuando el balance de beneficios supera danos.", "Buscar enfermedad tambien debe tener metodo."),
    s("La salud mental no es solo ausencia de trastorno", "Incluye capacidad de funcionar, relacionarse, adaptarse y encontrar sentido.", "Permite pensar bienestar antes de llegar a crisis.", "No significa estar feliz todo el tiempo.", "Terapia, apoyo social, descanso y rutinas pueden formar parte del cuidado.", "Estar bien no es no sentir nada malo.")
  ]
};

const ANGLES = [
  {
    label: "Concepto",
    title: (seed) => seed.topic,
    body: (seed) => seed.core,
    extra: (seed) => seed.memory
  },
  {
    label: "Impacto",
    title: (seed) => seed.topic,
    body: (seed) => seed.why,
    extra: () => "La gracia esta en conectar el dato con sus consecuencias."
  },
  {
    label: "Matiz",
    title: (seed) => seed.topic,
    body: (seed) => seed.trap,
    extra: () => "Los buenos datos suelen tener condiciones, limites y contexto."
  },
  {
    label: "Ejemplo",
    title: (seed) => seed.topic,
    body: (seed) => seed.example,
    extra: () => "Un ejemplo concreto hace que la idea deje de flotar."
  },
  {
    label: "Clave",
    title: (seed) => seed.topic,
    body: (seed) => seed.memory,
    extra: () => "Si puedes explicarlo en una frase, ya tienes una pieza mental util."
  }
];

function slugify(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const generatedFacts = [];

Object.entries(THEME_SEEDS).forEach(([category, seeds]) => {
  seeds.forEach((seed, seedIndex) => {
    ANGLES.forEach((angle, angleIndex) => {
      generatedFacts.push({
        id: `${slugify(category)}-${ACTIVE_PACK_ID}-${seedIndex + 1}-${angleIndex + 1}`,
        category,
        title: angle.title(seed),
        body: angle.body(seed),
        extra: angle.extra(seed),
        angle: angle.label,
        pack: ACTIVE_PACK_ID
      });
    });
  });
});

window.SABERSWIPE_CONTENT = {
  id: ACTIVE_PACK_ID,
  label: ACTIVE_PACK_LABEL,
  categories: Object.keys(THEME_SEEDS),
  facts: generatedFacts
};
